#!/bin/bash
cd /Users/devingearing/Documents/Arduino/WebControlledLEDs
git add .
clear
echo Please Enter GitHub Comment 
echo -n Input: 
read commitU
git commit -m “$commitU”
git push -u origin master
exit
